name: ACNN2
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - alembic==1.17.2
      - anyio==4.11.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - colorlog==6.10.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - detectors==0.1.11
      - faiss-cpu==1.13.0
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.4
      - idna==3.11
      - imageio==2.37.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - littleutils==0.2.4
      - mako==1.3.10
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.5
      - ogb==1.3.6
      - optuna==4.6.0
      - outdated==0.2.2
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pipdeptree==2.30.0
      - protobuf==6.33.1
      - psutil==7.1.3
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - timm==1.0.22
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wilds==2.0.0
prefix: D:\Windows_Folders\FACULTATE\Anaconda\envs\ACNN2
